### ISSUE TITLE
What may cause the exporter to OOM?

### ISSUE THREAD

**Issue by alfieyfc** [Strech/sidekiq-prometheus-exporter#37]
We are seeing some spikes in RAM consumption with both `0.1.13` and `0.1.15` versions, wondering what could've caused them.

![image](https://user-images.githubusercontent.com/41598103/108190415-dfbb9d80-714c-11eb-819f-0e98e301faf4.png)

While running under our K8s setup policies (requiring resource limitations), these spikes causes `sidekiq-prometheus-exporter` pods to exit with OOM, then restart, but no significant logs to be observed. We've tried setting memory limits for the container from 500Mi to 4Gi, however even with 4Gi this still happens, which seems odd since we didn't expect an exporter to consume so much resource.

I'm submitting this issue hoping to understand what types of events could trigger the exporter to consume more RAM than usual.

**Comment by Strech** [comment]
Hello @alfieyfc we can identify it by answering a list of questions:

1. Which metrics are you using? Only `standard`?
2. How many sidekiq queues do you have?
3. How many sidekiq workers do you have?

In `standard` metrics only 3 are not pre-calculated. It's `sidekiq_queue_latency_seconds`, `sidekiq_queue_enqueued_jobs` and `sidekiq_queue_max_processing_time_seconds`. They are using [Sidekiq API](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/api.rb) to get most of the abstractions, but it has a cost.

P.S if you like the project you can [support it ❤️](https://github.com/Strech/sidekiq-prometheus-exporter#if-you-like-the-project-and-want-to-support-me-on-my-sleepless-nights-you-can), any help is appreciated

**Comment by alfieyfc** [comment]
Hi @Strech Thanks for the reply!

We looked at the settings and verified with monitoring dashboard, that 
1. We're indeed using `standard` metrics only
2. We have 33 queues defined in our config yaml. However I noticed the metrics `sidekiq_queue` can vary depending on the queue. Not really sure where this metrics is defined since it's not in this repo's readme.
3. Using the metrics `sidekiq_workers` we see the numbers vary over time, most of the time it's about 100 and goes up to 280 at max

Looking just at the dashboard, I haven't been able to tell the correlations between exporter memory usage and any of the above :( Currently my plan is to observe correlations with sidekiq instances, but tbh I'm just aiming cluelessly... 

![image](https://user-images.githubusercontent.com/41598103/108458157-042f8b00-72af-11eb-9cdd-bba851278b5c.png)

I'll keep investigating and share any further progress here.

**Comment by Strech** [comment]
@alfieyfc Do I understand graphs correct that `Memory Usage`'s red line is an exporter memory usage and it jumps to 1Gb?

> We have 33 queues defined in our config yaml. However I noticed the metrics sidekiq_queue can vary depending on the queue. Not really sure where this metrics is defined since it's not in this repo's readme.

It's indeed not in the project. Can you tell me what's written in `sidekiq_queue` metrics? Because I don't have such a metric defined.

And how do you calculate the memory usage of the pod? Because Graphana may draw the spikes like that randomly and re-drawing them on reload. So can you share:

1. Which statement is written for `sidekiq_queue` metric
2. How you compute memory usage of the `metrics` pod
3. What the `metrics` pod restarted? Do you see it in k8s?

**Comment by Strech** [comment]
About `sidekiq_queue` seems like it's a copy of `sidekiq_queue_enqueued_jobs` and might be obsolete

**Comment by alfieyfc** [comment]
@Strech Sorry I was out during the weekend, here are my feedbacks on stuff:
1. You were correct on reading `Memory Usage`'s red line jumping, but it's not really about above or below 1GB. It jumps several times over a period, which to me is reasonable if they are using Sidekiq API to get most of the abstractions with a cost. However, we need to somewhat "predict" how much it consumes is considered "normal". 
Using the screenshot as an example, there were jumps over 1GB two times. Should we set the K8s Pod's `spec.containers[].resources.limits.memory` set to 1Gi, the Pod would crash with an OOM error.
As mentioned in original issue, setting `spec.containers[].resources.limits.memory` to 4Gi still encountered OOM since the exporter's consumption is over 4GB from time to time.
2. The `Memory Usage` is using 
    ```
    container_memory_usage_bytes{namespace="default",pod=~"sidekiq-prometheus-exporter-.*"}
    ```
    `container_memory_usage_bytes` I believe is from the `node-exporter`s
3. I'm not quite sure what you meant by `the metrics pod restarted`. In K8s, all we're seeing is
    ```bash
    $ kubectl get po
    NAME                                                         READY   STATUS      RESTARTS
    sidekiq-prometheus-exporter-7b64fc6c5d-gwprc                 1/1     Running     4
    ```
    ```bash
    $ kubectl describe po sidekiq-prometheus-exporter-7b64fc6c5d-gwprc        ## I'm skipping unrelated output
    Containers:
      sidekiq-prometheus-exporter:
        Last State:     Terminated
          Reason:       OOMKilled
          Exit Code:    137
    ```
4. Also not sure where to go with `how do you run the metrics pod?` The `sidekiq-prometheus-exporter` was directly pulled from your DockerHub repo, and run it in K8s with a YAML configuration file. I don't know what a `rack file` is 😅 The YAML looks something like this:
    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
    labels:
        app: sidekiq-prometheus-exporter
    name: sidekiq-prometheus-exporter
    namespace: default
    spec:
    replicas: 1
    selector:
        matchLabels:
        app: sidekiq-prometheus-exporter
    template:
        metadata:
        annotations:
            prometheus.io/port: "9292"
            prometheus.io/scrape: "true"
        labels:
            app: sidekiq-prometheus-exporter
        spec:
        containers:
        - env:
            - name: REDIS_URL
            value: redis://my-redis-sidekiq-svc:6379
            - name: LINES
            value: "42"
            - name: COLUMNS
            value: "178"
            image: strech/sidekiq-prometheus-exporter:0.1.15
            name: sidekiq-prometheus-exporter
            ports:
            - containerPort: 9292
            protocol: TCP
            resources:
            limits:
                cpu: 100m
                memory: 1Gi
            requests:
                cpu: 50m
                memory: 200Mi
    ```
