### ISSUE TITLE
Couldn't find handler for: puma, thin, falcon, webrick. (LoadError)

### ISSUE THREAD

**Issue by Jorijn** [Strech/sidekiq-prometheus-exporter#64]
Hi,

I deployed the exporter using Helm. The deployment fails to load:

```
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/handler.rb:45:in `pick': Couldn't find handler for: puma, thin, falcon, webrick. (LoadError)
```

Helm values:

```yaml
serviceMonitor:
  enabled: true
  interval: 15s

envFrom:
  type: secretRef
  name: sidekiq-metrics
```

Image: `docker.io/strech/sidekiq-prometheus-exporter:0.2.0`

It's connecting using TLS.

Do you have any idea what's happening? :)
